### ISSUE TITLE
Image preview in cmd

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [chrisant996/clink-fzf#22]
Is there any easy way to add a preview images in cmd? The documentation mentions something [about this](https://github.com/junegunn/fzf?tab=readme-ov-file#previewing-an-image), but there is only a [.sh example](https://github.com/junegunn/fzf/blob/master/bin/fzf-preview.sh).

**Comment by chrisant996** [comment]
You would need a terminal that can support non-text terminal content.  That's non-standard, and no terminals in Windows support non-text content.  Some terminals in Linux have special extensions to allow showing some kind of non-text content. 

The question is about terminals and operating systems, rather than about fzf (or Clink or clink-fzf).

**Comment by ArkadiuszMichalski** [comment]
I thought it was more popular these days. In the case of ConEmu there is issue for Sixel support:
https://github.com/Maximus5/ConEmu/issues/807
https://www.arewesixelyet.com/

**Comment by ArnaudKunzi** [comment]
There is also support in wezterm, though it seems broken at the moment?  It works trough the internal command `wezterm imgcat` although not necessarily through third party sixel programs.

**Comment by chrisant996** [comment]
The `fzf-preview.sh` script is essentially just a wrapper script to check which text or graphics programs are available, check the file type, and then use one of the programs to generate a preview.

One of the graphics programs it looks for is [chafa](https://hpjansson.org/chafa), which has a native Windows version.

Chafa is able to produce sixel output.  I understand sixel support is coming soon to Windows Terminal, so that will be pretty interesting.

But in the meantime, chafa can produce other lower-fidelity block graphic image conversions.  The default scale is 4.0 when using block graphics.

Original | Chafa default scale (4.0) | Chafa 2.0 scale | Chafa 1.0 scale
-|-|-|-
![RickAvatar](https://github.com/user-attachments/assets/ec60fd58-03a4-4409-950c-34ff516cd96c) | ![image](https://github.com/user-attachments/assets/8b66c776-1f0f-4259-bbd1-9e3047cc7783) | ![image](https://github.com/user-attachments/assets/8979e03e-ac03-42d1-b9ab-37551bf24aa5) | ![image](https://github.com/user-attachments/assets/608113b7-5a90-408e-8245-b0f46ac6c1c7)

So hey, that's interesting, even without sixel support.

I'll look into making some similar `fzf-preview.cmd` script.  It will probably rely on [bat](https://github.com/sharkdp/bat) for text files, and [chafa](https://hpjansson.org/chafa) for image files.

Since the spirit of fzf is to be highly customizable, and because previewing will depend on other programs which might not exist, I probably will not build in file preview "out of the box".  Instead, just like with `fzf` itself, it will be require a tiny amount of customization, which can be shown in the README.md file (which already shows some customizations).

**Comment by chrisant996** [comment]
The [README.md](https://github.com/chrisant996/clink-fzf#previewing-image-files) file has been updated with instructions for how to configure previewing image files using the newly added [fzf-preview.cmd](https://github.com/chrisant996/clink-fzf/blob/main/fzf-preview.cmd) script.

**Comment by chrisant996** [comment]
(When sixel support becomes available in Windows Terminal, the script can be updated accordingly.)
